name: terraform-lint

on: [push, pull_request]

jobs:
  #linter
  linter:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Lint Terraform
      uses: actionshub/terraform-lint@main
  
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV_INFRA }}
        SLACK_MESSAGE: 'Terraform linter'
        SLACK_TITLE: 'workflow'
        SLACK_USERNAME: 'Github_Action'
        SLACK_COLOR: ${{ job.status }}