# This is a basic workflow to help you get started with Actions

name: fil_rouge_deployment_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  resourcegroups:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: 'Deployment test'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_environments: '["${{ github.run_id }}${{ github.run_attempt }}"]'
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 'Terraform init'
        id: init
        run: |
          terraform init

      - name: 'Terraform validate'
        id: validate
        run: |
          terraform validate -no-color

      - name: 'Terraform plan'
        id: plan
        run: |
          terraform plan
        continue-on-error: true
                    
      - name: 'Terraform apply'
        id: apply
        run: |
          terraform apply -auto-approve
        continue-on-error: true
                    
      - name: 'Terraform destroy'
        id: destroy
        run: |
          terraform destroy -auto-approve
    slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV_INFRA }}
        SLACK_MESSAGE: 'déploiement de l'environnement de développement'
        SLACK_TITLE: 'workflow'
        SLACK_USERNAME: 'Github_Action'
        SLACK_COLOR: ${{ job.status }}